import{a as g,i as l,S as E}from"./assets/vendor-BHdvj17y.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();let u=1;async function p(r,e){g.defaults.baseURL="https://pixabay.com";const a={key:"49676421-fbb984ce693a0b40b5728e81f",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};try{const s=await g.get("/api/",{params:a}),{total:t,totalHits:o,hits:n}=s.data;return u=Math.ceil(o/a.per_page),!n||n.length===0?(l.warning({title:"❌",message:"Sorry, no images match your search query. Please try again!",color:"red",position:"topRight",messageColor:"white",titleColor:"white"}),{total:t,totalHits:o,hits:[],error:null}):{total:t,totalHits:o,hits:n,error:null}}catch(s){return l.error({title:"Error",message:s.message,color:"red",position:"topRight",messageColor:"white",titleColor:"white"}),{total:0,totalHits:0,hits:[],error:s.message}}}const d=document.querySelector(".loader"),f=document.querySelector(".gallery"),h=document.querySelector(".load-more");d&&(d.hidden=!0);const y=new E(".gallery-item a",{captionsData:"alt",captionDelay:250});function R(r){const e=v(r);f.insertAdjacentHTML("afterbegin",e),y.refresh()}function q(r){const e=v(r);f.insertAdjacentHTML("beforeend",e),y.refresh()}function M(){f.innerHTML=""}function w(r){d.hidden=!1,r>1&&d.classList.add("load-more-loader")}function L(){d.hidden=!0}function b(r){r<u?$():u&&(c(),l.info({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight",messageColor:"black"}))}function S(){let e=f.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,left:0,behavior:"smooth"})}function $(){h.classList.add("is-visible")}function c(){h.classList.remove("is-visible")}function P(r){const{webformatURL:e,largeImageURL:a,tags:s,likes:t,views:o,comments:n,downloads:C}=r;return`<li class="gallery-item">
  <a class="gallery-link" href="${a}">
    <img
      class="gallery-image"
      src="${e}"
      alt="${s}"
    />
  </a><div class="stats">
  <p class="img-rates">Likes<span>${t}</span></p>
  <p class="img-rates">Views<span>${o}</span></p>
  <p class="img-rates">Comments<span>${n}</span></p>
  <p class="img-rates">Downloads<span>${C}</span></p></div>
</li>
`}function v(r){return r.map(P).join(`
`)}const A=document.querySelector(".form"),B=document.querySelector(".load-more");let i,m;A.addEventListener("submit",async r=>{if(r.preventDefault(),m=r.currentTarget.elements["search-text"].value.trim(),!m)return l.info({message:"Введіть запит",color:"red",position:"topRight",messageColor:"white",titleColor:"white"});M(),c(),i=1;try{w(i);const{hits:e,totalHits:a,error:s}=await p(m,i);if(s)return;e.length>0&&(R(e),i>=u&&(c(),l.info({message:"You've reached the end of search results.",position:"topRight"})))}catch(e){l.error({message:e.message,color:"red",position:"topRight",messageColor:"white",titleColor:"white"}),c()}finally{L(),b(i)}});B.addEventListener("click",async r=>{i+=1,c();try{w(i);const{hits:e,error:a}=await p(m,i);if(a)return;e.length>0&&(q(e),S(),i>=u&&(c(),l.info({message:"You've reached the end of search results.",position:"topRight"})))}catch(e){l.error({message:e.message,color:"red",position:"topRight",messageColor:"white",titleColor:"white"}),c()}finally{L(),b(i)}});
//# sourceMappingURL=index.js.map
